
AWSTemplateFormatVersion: '2010-09-09'
Description: Notification to Slack

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Base Setting
        Parameters:
          - ENV
          - ServiceName
      - Label:
          default: Subscriptions Parameters
        Parameters:
          - SubsciptionLambdaFunctionArn
          - SubsciptionMailAddress
      - Label:
          default: Options
        Parameters:
          - MigrationHubServerID

#スタックパラメーター設定
Parameters:
  #環境名
  ENV:
    Type: String
    AllowedValues: ['prod', 'stg', 'dev']
    ConstraintDescription: Enter prod, stg, or dev."
  #サービス名
  ServiceName:
    Type: String
    AllowedPattern: ^[a-z0-9-]*$
    Default: play-store
    ConstraintDescription: Malformed input-Parameter ServiceName must match pattern [a-z0-9-]+
    Description: Enter service name, like 「play-store」

  # SNS Topic サブスクリプション用Lambda
  SubsciptionLambdaFunctionArn:
    Type: String
    Description: Enter lambda function arn, like 「arn:aws:lambda:ap-northeast-1:xxxx:function:xxxxxxx」

  # SNS Topic サブスクリプション用メールアドレスs
  SubsciptionMailAddress:
    Type: String
    AllowedPattern: ^[a-zA-Z0-9_+-]+(.[a-zA-Z0-9_+-]+)*@([a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\.)+[a-zA-Z]{2,}$
    Default: playstores_dev@play.jp
    Description: Enter e-mail address, like ?playstores_dev@play.jp?

  # MigrationHubServerID
  MigrationHubServerID:
    Type: String
    Description: Enter Migration Hub Server ID, like 「d-server-000zia7b0qhil8」
    Default: ''

Conditions:
  HasNotSubscriptionLambda: !Equals [!Ref SubsciptionLambdaFunctionArn, '']
  HasNotSubsciptionMailAddress: !Equals [!Ref SubsciptionMailAddress, '']
  HasMigrationHubServerID: !Not [!Equals [!Ref MigrationHubServerID, '']]

Resources:
###################################### SNS ############################################

  # CloudWatch Alarm用 SNS Topic
  CloudWatchAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${ServiceName}-${ENV}-cloudwatch-alarm-sns-topic
      Subscription: !If
        - HasNotSubscriptionLambda
        # Lambda for Slack
        - !Ref 'AWS::NoValue'
        - - Endpoint: !Ref SubsciptionLambdaFunctionArn
            Protocol: "lambda"
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-${ENV}-cloudwatch-alarm-sns-topic
        - Key: ENV
          Value: !Ref ENV
        - Key: Project
          Value: !Ref ServiceName
        - !If
          - HasMigrationHubServerID
          - Key: map-migrated
            Value: !Ref MigrationHubServerID
          - !Ref AWS::NoValue

  # CloudWatch Alarm用 SNS Topic
  CostAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${ServiceName}-${ENV}-cost-alarm-sns-topic
      Subscription:  !If
        - HasNotSubsciptionMailAddress
        - !Ref 'AWS::NoValue'
        - - Endpoint: !Ref SubsciptionMailAddress
            Protocol: "email"
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-${ENV}-cost-alarm-sns-topic
        - Key: ENV
          Value: !Ref ENV
        - Key: Project
          Value: !Ref ServiceName
        - !If
          - HasMigrationHubServerID
          - Key: map-migrated
            Value: !Ref MigrationHubServerID
          - !Ref AWS::NoValue

Outputs:
  CloudWatchAlarmTopicArn:
    Value: !Ref CloudWatchAlarmTopic
    Export:
      Name: !Sub ${ServiceName}-${ENV}-cloudwatch-alarm-topic
  CostAlarmTopicArn:
    Value: !Ref CostAlarmTopic
    Export:
      Name: !Sub ${ServiceName}-${ENV}-cost-alarm-topic
