
AWSTemplateFormatVersion: '2010-09-09'
Description: Notification to Slack

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Base Setting
        Parameters:
          - ENV
          - ServiceName
      - Label:
          default: ChatBot Base Parameters
        Parameters:
          - WorkspaceId
      - Label:
          default: ChatBot Parameters For Critical Alarm
        Parameters:
          - CriticalAlarmChannelId
          - CriticalAlarmSnsTopicArns
      - Label:
          default: ChatBot Parameters For Warning Alarm
        Parameters:
          - WarningAlarmChannelId
          - WarningAlarmSnsTopicArns

#スタックパラメーター設定
Parameters:
  #環境名
  ENV:
    Type: String
    AllowedValues: ['prod', 'stg', 'dev']
    ConstraintDescription: Enter prod, stg, or dev."
  #サービス名
  ServiceName:
    Type: String
    AllowedPattern: ^[a-z0-9-]*$
    Default: rare-light
    ConstraintDescription: Malformed input-Parameter ServiceName must match pattern [a-z0-9-]+
    Description: Enter service name, like 「rare-light」

  # SlackのワークスペースID
  WorkspaceId:
    Type: String
    Description: Enter chatbot slack workspaseID, like 「T024XKAKS」

  # Criticalアラート通知用 SlackのチャンネルID
  CriticalAlarmChannelId:
    Type: String
    Description: Enter send slack channelID, like 「C018C8P7TLM」

  # Criticalアラート通知用 SNSトピック
  CriticalAlarmSnsTopicArns:
    Type: CommaDelimitedList
    Description: Enter sns topic list, like 「arn:aws:sns:ap-northeast-1:<accountId>:<topicName>」

  # Warningアラート通知用 SlackのチャンネルID
  WarningAlarmChannelId:
    Type: String
    Description: Enter send slack channelID, like 「C018C8P7TLM」

  # Warningアラート通知用 SNSトピック
  WarningAlarmSnsTopicArns:
    Type: CommaDelimitedList
    Description: Enter sns topic list, like 「arn:aws:sns:ap-northeast-1:<accountId>:<topicName>」

Conditions:
  HasCriticalAlarmSnsTopicArns: !Not
    - !Equals
      - !Join ["", !Ref CriticalAlarmSnsTopicArns]
      - ''
  HasWarningAlarmSnsTopicArns: !Not
    - !Equals
      - !Join ["", !Ref WarningAlarmSnsTopicArns]
      - ''
  DiffAlarmChannelId: !Not
  - !Equals
    - !Ref CriticalAlarmChannelId
    - !Ref WarningAlarmChannelId

Resources:

###################################### Chatbot ############################################

  # Criticalアラート通知用 Chatbot
  CloudWatchAlarmForChatbot:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties:
      ConfigurationName: !Sub ${ServiceName}-${ENV}-cloudwatch-chatbot-for-cloudwatch-alarm
      IamRoleArn: !GetAtt ChatbotIamRole.Arn
      LoggingLevel: INFO
      SlackChannelId: !Ref CriticalAlarmChannelId
      SlackWorkspaceId: !Ref WorkspaceId
      SnsTopicArns: !If
        - HasCriticalAlarmSnsTopicArns
        - !Ref CriticalAlarmSnsTopicArns
        - !Ref AWS::NoValue

  # Warningアラート通知用 Chatbot
  WarningAlarmForChatbot:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Condition: DiffAlarmChannelId
    Properties:
      ConfigurationName: !Sub ${ServiceName}-${ENV}-cloudwatch-chatbot-for-warning-alarm
      IamRoleArn: !GetAtt ChatbotIamRole.Arn
      LoggingLevel: INFO
      SlackChannelId: !Ref WarningAlarmChannelId
      SlackWorkspaceId: !Ref WorkspaceId
      SnsTopicArns: !If
        - HasWarningAlarmSnsTopicArns
        - !Ref WarningAlarmSnsTopicArns
        - !Ref AWS::NoValue

###################################### IAM Role ############################################

  # Chatbotで利用するIAMロールの定義
  ChatbotIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${ENV}-cloudwatch-chatbot-iam-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: chatbot.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: chatbot-iam-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:Describe*
                  - cloudwatch:Get*
                  - cloudwatch:List*
                  - logs:*
                Resource:
                  - "*"
