AWSTemplateFormatVersion: '2010-09-09'
#スタックパラメーター設定
Parameters:
  #環境名
  ENV:
    Type: String
    AllowedValues: ['prod', 'stg', 'dev']
    ConstraintDescription: Enter prod, stg, or dev."

  #サービス名
  ServiceName:
    Type: String
    AllowedPattern: ^[a-z0-9-]*$
    Default: play-store
    ConstraintDescription: Malformed input-Parameter ServiceName must match pattern [a-z0-9-]+
    Description: Enter service name, like 「play-store」

  #システム名
  SystemName:
    Type: String
    AllowedPattern: ^[a-z0-9-]*$
    ConstraintDescription: Malformed input-Parameter SystemName must match pattern [a-z0-9-]+
    Description: Enter service name, like 「venus-api」

  # Project ID
  ProjectId:
    Type: String
    AllowedPattern: ^[a-z0-9-_]*$
    ConstraintDescription: Malformed input-Parameter ProjectId must match pattern [a-z0-9-_]+
    Description: Enter project id, like 「tipness」,「shiki」

  AllowedIps:
    Description: Comma-separated list of allowed IP CIDR blocks. The default addresses listed are BitBucket Cloud IP ranges.
    Type: CommaDelimitedList
    Default: 113.43.239.66/32,122.221.102.154/32,113.42.102.154/32,124.36.35.82/32

Resources:
  # Closed IPset for CloudFront
  CFWAFv2IPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Addresses: !Ref AllowedIps
      Description: !Sub ${ServiceName}-${ENV}-${SystemName} IPset to CloudFront closed
      IPAddressVersion: IPV4
      Name: !Sub ${ServiceName}-${ENV}-${SystemName}-cf-closed
      Scope: CLOUDFRONT
      Tags:
      - Key: Name
        Value: !Sub ${SystemName}-${ENV}-ipset
      - Key: ENV
        Value: !Ref ENV
      - Key: Project
        Value: !Ref ServiceName
      - Key: SystemName
        Value: !Ref SystemName
      - Key: ProjectId
        Value: !Ref ProjectId

Outputs:
  CFIPsetArn:
    Value: !GetAtt 'CFWAFv2IPSet.Arn'
    Export:
      Name: !Sub ${ServiceName}-${ENV}-${SystemName}-ipset-arn
  CFIPsetId:
    Value: !GetAtt 'CFWAFv2IPSet.Id'
    Export:
      Name: !Sub ${ServiceName}-${ENV}-${SystemName}-ipset-id