AWSTemplateFormatVersion: '2010-09-09'
#スタックパラメーター設定
Parameters:
  #環境名
  ENV:
    Type: String
    AllowedValues: ['prod', 'stg', 'dev']
    ConstraintDescription: Enter prod, stg, or dev."

  #サービス名
  ServiceName:
    Type: String
    AllowedPattern: ^[a-z0-9-]*$
    Default: play-store
    ConstraintDescription: Malformed input-Parameter ServiceName must match pattern [a-z0-9-]+
    Description: Enter service name, like 「play-store」

  #システム名
  SystemName:
    Type: String
    AllowedPattern: ^[a-z0-9-]*$
    ConstraintDescription: Malformed input-Parameter SystemName must match pattern [a-z0-9-]+
    Description: Enter service name, like 「venus-api」

  # Project ID
  ProjectId:
    Type: String
    AllowedPattern: ^[a-z0-9-_]*$
    ConstraintDescription: Malformed input-Parameter ProjectId must match pattern [a-z0-9-_]+
    Description: Enter project id, like 「tipness」,「shiki」

Resources:
  # WEB ACL
  WAFv2WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Block: {}
      Name: !Sub  ${ServiceName}-${ENV}-${SystemName}-webacl
      Description: !Sub ${ServiceName}-${ENV}-${SystemName} WebACL
      Rules:
        - Name: !Sub ${ServiceName}-${ENV}-${SystemName}-cf-rule
          Action:
              Allow: {}
          Priority: 0
          Statement:
            IPSetReferenceStatement:
              Arn:
                Fn::ImportValue: !Sub ${ServiceName}-${ENV}-${SystemName}-ipset-arn
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${ServiceName}-${ENV}-${SystemName}-cf-closed
            SampledRequestsEnabled: true
      Scope: "CLOUDFRONT"
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: !Sub ${ServiceName}-${ENV}-${SystemName}-webacl
        SampledRequestsEnabled: true
      Tags:
      - Key: Name
        Value: !Sub ${SystemName}-${ENV}-webacl
      - Key: ENV
        Value: !Ref ENV
      - Key: Project
        Value: !Ref ServiceName
      - Key: SystemName
        Value: !Ref SystemName
      - Key: ProjectId
        Value: !Ref ProjectId

Outputs:
  WebACLArn:
    Value: !GetAtt 'WAFv2WebACL.Arn'
    Export:
      Name: !Sub ${ServiceName}-${ENV}-${SystemName}-webacl-arn
  WebACLId:
    Value: !GetAtt 'WAFv2WebACL.Id'
    Export:
      Name: !Sub ${ServiceName}-${ENV}-${SystemName}-webacl-id