AWSTemplateFormatVersion: '2010-09-09'
#スタックパラメーター設定
Parameters:
  #環境名
  ENV:
    Type: String
    AllowedValues: ['prod', 'stg', 'dev']
    ConstraintDescription: Enter prod, stg, or dev."

  #サービス名
  ServiceName:
    Type: String
    AllowedPattern: ^[a-z0-9-]*$
    Default: play-store
    ConstraintDescription: Malformed input-Parameter ServiceName must match pattern [a-z0-9-]+
    Description: Enter service name, like 「play-store」

Resources:
  # CloudFront Logs on S3 Bucket
  CFLogsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${ServiceName}-${ENV}-cf-logs-bucket
      LifecycleConfiguration:
        Rules:
          - Id: S3LifecycleRule
            Status: Enabled
            ExpirationInDays: 366
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  CFLogsBucketName:
    Value: !Ref CFLogsBucket
    Export:
      Name: !Sub ${ServiceName}-${ENV}-cf-logs-bucket
  CFLogsBucketArn:
    Value: !GetAtt 'CFLogsBucket.Arn'
    Export:
      Name: !Sub ${ServiceName}-${ENV}-cf-logs-arn
  CFLogsBucketDomainName:
    Value: !GetAtt 'CFLogsBucket.DomainName'
    Export:
      Name: !Sub ${ServiceName}-${ENV}-cf-logs-domain