AWSTemplateFormatVersion: '2010-09-09'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Base Setting
        Parameters:
          - ENV
          - ServiceName
      - Label:
          default: Options
        Parameters:
          - MigrationHubServerID

#スタックパラメーター設定
Parameters:
  #環境名
  ENV:
    Type: String
    AllowedValues: ['prod', 'stg', 'dev']
    ConstraintDescription: Enter prod, stg, or dev."

  #サービス名
  ServiceName:
    Type: String
    AllowedPattern: ^[a-z0-9-]*$
    Default: pvs
    ConstraintDescription: Malformed input-Parameter ServiceName must match pattern [a-z0-9-]+
    Description: Enter service name, like 「pvs」

  # MigrationHubServerID
  MigrationHubServerID:
    Type: String
    ConstraintDescription: Malformed Input-Parameter must match pattern [a-z0-9-_]+
    Description: Enter Migration Hub Server ID, like 「d-server-000zia7b0qhil8」
    Default: ''

Conditions:
  HasMigrationHubServerID: !Not [!Equals [!Ref MigrationHubServerID, '']]

Resources:
  # CloudFront Logs on S3 Bucket
  CFLogsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${ServiceName}-${ENV}-cf-logs-bucket
      LifecycleConfiguration:
        Rules:
          - Id: S3LifecycleRule
            Status: Enabled
            ExpirationInDays: 366
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
      - Key: Name
        Value: !Sub ${ServiceName}-${ENV}-cf-logs-bucket
      - Key: ENV
        Value: !Ref ENV
      - Key: Project
        Value: !Ref ServiceName
      - !If
        - HasMigrationHubServerID
        - Key: map-migrated
          Value: !Ref MigrationHubServerID
        - !Ref AWS::NoValue

  ######################### Stores on S3 Bucket #########################

  StoresBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${ServiceName}-${ENV}-stores-bucket-${AWS::Region}
      LifecycleConfiguration:
        Rules:
          - Id: !Sub ${ServiceName}-${ENV}-stores-lifecycle
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      MetricsConfigurations:
        - Id: !Sub ${ServiceName}-${ENV}-stores-metrics-all
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-${ENV}-stores-bucket-${AWS::Region}
        - Key: ENV
          Value: !Ref ENV
        - Key: Project
          Value: !Ref ServiceName
        - !If
          - HasMigrationHubServerID
          - Key: map-migrated
            Value: !Ref MigrationHubServerID
          - !Ref AWS::NoValue

  # S3Bucket Policy To Allow Access From CloudFront OAI
  StoresBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StoresBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${StoresBucket}/*
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${StoresBucketOriginAccessIdentity}

  # StoresBucket Origin Access Identity
  StoresBucketOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub ${ServiceName}-${ENV}-stores-bucket-identity


  ######################### NEW Stores on S3 Bucket #########################

  StoreSettingsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${ServiceName}-${ENV}-stores-${AWS::Region}
      LifecycleConfiguration:
        Rules:
          - Id: !Sub ${ServiceName}-${ENV}-stores-lifecycle
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      MetricsConfigurations:
        - Id: !Sub ${ServiceName}-${ENV}-stores-metrics-all
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-${ENV}-stores-${AWS::Region}
        - Key: ENV
          Value: !Ref ENV
        - Key: Project
          Value: !Ref ServiceName
        - !If
          - HasMigrationHubServerID
          - Key: map-migrated
            Value: !Ref MigrationHubServerID
          - !Ref AWS::NoValue

  # S3Bucket Policy To Allow Access From CloudFront OAI
  StoreSettingsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StoreSettingsBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${StoreSettingsBucket}/*
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${StoreSettingsBucketOriginAccessIdentity}

  # StoreSettingsBucket Origin Access Identity
  StoreSettingsBucketOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub ${ServiceName}-${ENV}-stores-identity

  ######################### Sitemap on S3 Bucket #########################

  SitemapBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${ServiceName}-${ENV}-sitemap-bucket
      LifecycleConfiguration:
        Rules:
          - Id: !Sub ${ServiceName}-${ENV}-sitemap-lifecycle
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-${ENV}-sitemap-bucket
        - Key: ENV
          Value: !Ref ENV
        - Key: Project
          Value: !Ref ServiceName
        - !If
          - HasMigrationHubServerID
          - Key: map-migrated
            Value: !Ref MigrationHubServerID
          - !Ref AWS::NoValue

  # S3Bucket Policy To Allow Access From CloudFront OAI
  SitemapBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SitemapBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${SitemapBucket}/*
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${SitemapBucketOriginAccessIdentity}

  # SitemapBucket Origin Access Identity
  SitemapBucketOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub ${ServiceName}-${ENV}-sitemap-identity

  ######################### Sorry Pages on S3 Bucket #########################

  SorryPagesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${ServiceName}-${ENV}-sorry-pages-bucket
      LifecycleConfiguration:
        Rules:
          - Id: !Sub ${ServiceName}-${ENV}-stores-lifecycle
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-${ENV}-sorry-pages-bucket
        - Key: ENV
          Value: !Ref ENV
        - Key: Project
          Value: !Ref ServiceName
        - !If
          - HasMigrationHubServerID
          - Key: map-migrated
            Value: !Ref MigrationHubServerID
          - !Ref AWS::NoValue

  # Stores Bucket Origin Access Identity
  SorryPagesBucketOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub ${ServiceName}-${ENV}-sorry-pages-identity

  # S3Bucket Policy To Allow Access From CloudFront OAI
  SorryPagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SorryPagesBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${SorryPagesBucket}/*
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${SorryPagesBucketOriginAccessIdentity}

  ######################### Static Files on S3 Bucket #########################

  StaticFilesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${ServiceName}-${ENV}-static-files-${AWS::Region}
      LifecycleConfiguration:
        Rules:
          - Id: !Sub ${ServiceName}-${ENV}-static-files-lifecycle
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      MetricsConfigurations:
        - Id: !Sub ${ServiceName}-${ENV}-static-files-metrics-all
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-${ENV}-static-files-${AWS::Region}
        - Key: ENV
          Value: !Ref ENV
        - Key: Project
          Value: !Ref ServiceName
        - !If
          - HasMigrationHubServerID
          - Key: map-migrated
            Value: !Ref MigrationHubServerID
          - !Ref AWS::NoValue

  # S3Bucket Policy To Allow Access From CloudFront OAI
  StaticFileBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticFilesBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${StaticFilesBucket}/*
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${StaticFilesBucketOriginAccessIdentity}

  # StaticFilesBucket Origin Access Identity
  StaticFilesBucketOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub ${ServiceName}-${ENV}-static-files-identity

Outputs:
  # CFLogsBucket
  CFLogsBucketName:
    Value: !Ref CFLogsBucket
    Export:
      Name: !Sub ${ServiceName}-${ENV}-cf-logs-bucket
  CFLogsBucketArn:
    Value: !GetAtt 'CFLogsBucket.Arn'
    Export:
      Name: !Sub ${ServiceName}-${ENV}-cf-logs-arn
  CFLogsBucketDomainName:
    Value: !GetAtt 'CFLogsBucket.DomainName'
    Export:
      Name: !Sub ${ServiceName}-${ENV}-cf-logs-domain

  # StoresBucket
  StoresBucketName:
    Value: !Ref StoresBucket
    Export:
      Name: !Sub ${ServiceName}-${ENV}-stores-bucket
  StoresBucketArn:
    Value: !GetAtt 'StoresBucket.Arn'
    Export:
      Name: !Sub ${ServiceName}-${ENV}-stores-bucket-arn
  StoresBucketDomainName:
    Value: !GetAtt 'StoresBucket.DomainName'
    Export:
      Name: !Sub ${ServiceName}-${ENV}-stores-bucket-domain
  StoresBucketOAI:
    Value: !Ref StoresBucketOriginAccessIdentity
    Export:
      Name: !Sub ${ServiceName}-${ENV}-stores-bucket-oai

  # StoreSettingsBucket
  StoreSettingsBucketArn:
    Value: !GetAtt 'StoreSettingsBucket.Arn'
    Export:
      Name: !Sub ${ServiceName}-${ENV}-stores-arn
  StoreSettingsBucketDomainName:
    Value: !GetAtt 'StoreSettingsBucket.DomainName'
    Export:
      Name: !Sub ${ServiceName}-${ENV}-stores-domain
  StoreSettingsBucketOAI:
    Value: !Ref StoreSettingsBucketOriginAccessIdentity
    Export:
      Name: !Sub ${ServiceName}-${ENV}-stores-oai

  # SitemapBucket
  SitemapBucketName:
    Value: !Ref SitemapBucket
    Export:
      Name: !Sub ${ServiceName}-${ENV}-sitemap-bucket
  SitemapBucketArn:
    Value: !GetAtt 'SitemapBucket.Arn'
    Export:
      Name: !Sub ${ServiceName}-${ENV}-sitemap-arn
  SitemapBucketDomainName:
    Value: !GetAtt 'SitemapBucket.DomainName'
    Export:
      Name: !Sub ${ServiceName}-${ENV}-sitemap-domain
  SitemapBucketOriginAccessIdentity:
    Value: !Ref SitemapBucketOriginAccessIdentity
    Export:
      Name: !Sub ${ServiceName}-${ENV}-sitemap-oai

  # SorryPagesBucket
  SorryPagesBucketName:
    Value: !Ref SorryPagesBucket
    Export:
      Name: !Sub ${ServiceName}-${ENV}-sorry-pages
  SorryPagesBucketArn:
    Value: !GetAtt 'SorryPagesBucket.Arn'
    Export:
      Name: !Sub ${ServiceName}-${ENV}-sorry-pages-arn
  SorryPagesBucketDomainName:
    Value: !GetAtt 'SorryPagesBucket.DomainName'
    Export:
      Name: !Sub ${ServiceName}-${ENV}-sorry-pages-domain
  SorryPagesBucketOriginAccessIdentity:
    Value: !Ref SorryPagesBucketOriginAccessIdentity
    Export:
      Name: !Sub ${ServiceName}-${ENV}-sorry-pages-oai

  # StaticFilesBucket
  StaticFilesBucketArn:
    Value: !GetAtt 'StaticFilesBucket.Arn'
    Export:
      Name: !Sub ${ServiceName}-${ENV}-static-files-arn
  StaticFilesBucketDomainName:
    Value: !GetAtt 'StaticFilesBucket.DomainName'
    Export:
      Name: !Sub ${ServiceName}-${ENV}-static-files-domain
  StaticFilesBucketOriginAccessIdentity:
    Value: !Ref StaticFilesBucketOriginAccessIdentity
    Export:
      Name: !Sub ${ServiceName}-${ENV}-static-files-oai