AWSTemplateFormatVersion: '2010-09-09'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Base Setting
        Parameters:
          - ENV
          - ServiceName

#スタックパラメーター設定
Parameters:
  #環境名
  ENV:
    Type: String
    AllowedValues: ['prod', 'stg', 'dev']
    ConstraintDescription: Enter prod, stg, or dev.'

  #サービス名
  ServiceName:
    Type: String
    AllowedPattern: ^[a-z0-9-]*$
    Default: pvs
    ConstraintDescription: Malformed input-Parameter ServiceName must match pattern [a-z0-9-]+
    Description: Enter service name, like 「pvs」

Resources:
  ####################################### Cache Policy ############################################
  ## Disabled Cache Policy
  DisabledCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
          Name: !Sub ${ServiceName}-${ENV}-disabled-cache-policy
          Comment: !Sub ${ServiceName}-${ENV}-disabled-cache-policy
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          ParametersInCacheKeyAndForwardedToOrigin:
            EnableAcceptEncodingBrotli: false
            EnableAcceptEncodingGzip: false
            HeadersConfig:
              HeaderBehavior: none
            CookiesConfig:
              CookieBehavior: none
            QueryStringsConfig:
              QueryStringBehavior: none

  ## Image Cache Policy
  ImageCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
          Name: !Sub ${ServiceName}-${ENV}-img-cache-policy
          Comment: !Sub ${ServiceName}-${ENV}-img-cache-policy
          DefaultTTL: 7200
          MaxTTL: 14400
          MinTTL: 300
          ParametersInCacheKeyAndForwardedToOrigin:
            EnableAcceptEncodingBrotli: true
            EnableAcceptEncodingGzip: true
            HeadersConfig:
              HeaderBehavior: none
            CookiesConfig:
              CookieBehavior: none
            QueryStringsConfig:
              QueryStringBehavior: none

  ## Assets Cache Policy
  AssetsCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
          Name: !Sub ${ServiceName}-${ENV}-assets-cache-policy
          Comment: !Sub ${ServiceName}-${ENV}-assets-cache-policy
          DefaultTTL: 600
          MaxTTL: 1800
          MinTTL: 300
          ParametersInCacheKeyAndForwardedToOrigin:
            EnableAcceptEncodingBrotli: true
            EnableAcceptEncodingGzip: true
            HeadersConfig:
              HeaderBehavior: none
            CookiesConfig:
              CookieBehavior: none
            QueryStringsConfig:
              QueryStringBehavior: none

  ## Js Cache Policy
  JsCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
          Name: !Sub ${ServiceName}-${ENV}-js-cache-policy
          Comment: !Sub ${ServiceName}-${ENV}-js-cache-policy
          DefaultTTL: 7200
          MaxTTL: 14400
          MinTTL: 300
          ParametersInCacheKeyAndForwardedToOrigin:
            EnableAcceptEncodingBrotli: true
            EnableAcceptEncodingGzip: true
            HeadersConfig:
              HeaderBehavior: none
            CookiesConfig:
              CookieBehavior: none
            QueryStringsConfig:
              QueryStringBehavior: none

  ## Disabled Cache Policy
  DefaultCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
          Name: !Sub ${ServiceName}-${ENV}-default-cache-policy
          Comment: !Sub ${ServiceName}-${ENV}-default-cache-policy
          DefaultTTL: 1
          MaxTTL: 1
          MinTTL: 1
          ParametersInCacheKeyAndForwardedToOrigin:
            EnableAcceptEncodingBrotli: true
            EnableAcceptEncodingGzip: true
            HeadersConfig:
              HeaderBehavior: none
            CookiesConfig:
              CookieBehavior: none
            QueryStringsConfig:
              QueryStringBehavior: none

  ## 1min Cache Policy
  1minCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
          Name: !Sub ${ServiceName}-${ENV}-1min-cache-policy
          Comment: !Sub ${ServiceName}-${ENV}-1min-cache-policy
          DefaultTTL: 60
          MaxTTL: 60
          MinTTL: 60
          ParametersInCacheKeyAndForwardedToOrigin:
            EnableAcceptEncodingBrotli: true
            EnableAcceptEncodingGzip: true
            HeadersConfig:
              HeaderBehavior: none
            CookiesConfig:
              CookieBehavior: none
            QueryStringsConfig:
              QueryStringBehavior: none

  ####################################### Origin request Policy ############################################
  ## Disabled Request Policy
  DisabledOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub ${ServiceName}-${ENV}-disabled-origin-request-policy
        Comment: !Sub ${ServiceName}-${ENV}-disabled-origin-request-policy
        HeadersConfig:
          HeaderBehavior: none
        CookiesConfig:
          CookieBehavior: none
        QueryStringsConfig:
          QueryStringBehavior: none

  ## All Viewer Policy
  AllViewerPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub ${ServiceName}-${ENV}-allviewer-policy
        Comment: !Sub ${ServiceName}-${ENV}-allviewer-policy
        HeadersConfig:
          HeaderBehavior: allViewer
        CookiesConfig:
          CookieBehavior: all
        QueryStringsConfig:
          QueryStringBehavior: all

  ## Geolocation Headers Policy !!!不要になったら削除する
  GeolocationHeadersPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub ${ServiceName}-${ENV}-geolocation-policy
        Comment: !Sub ${ServiceName}-${ENV}-geolocation-policy
        HeadersConfig:
          HeaderBehavior: whitelist
          Headers:
            - User-Agent
            - CloudFront-Viewer-Country
            - CloudFront-Viewer-Country-Name
            - CloudFront-Viewer-Country-Region
            - CloudFront-Viewer-Country-Region-Name
        CookiesConfig:
          CookieBehavior: all
        QueryStringsConfig:
          QueryStringBehavior: all

  ## Static Origin Policy
  StaticCachePolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub ${ServiceName}-${ENV}-static-origin-policy
        Comment: !Sub ${ServiceName}-${ENV}-static-origin-policy
        HeadersConfig:
          HeaderBehavior: allViewerAndWhitelistCloudFront
          Headers:
            - CloudFront-Viewer-Country
            - CloudFront-Viewer-Country-Name
            - CloudFront-Viewer-Country-Region
            - CloudFront-Viewer-Country-Region-Name
            - CloudFront-Viewer-City
        CookiesConfig:
          CookieBehavior: none
        QueryStringsConfig:
          QueryStringBehavior: all

  ## All Viewer And CloudFront Policy
  AllViewerAndCloudFrontPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub ${ServiceName}-${ENV}-allviewer-cloudfront-policy
        Comment: !Sub ${ServiceName}-${ENV}-allviewer-cloudfront-policy
        HeadersConfig:
          HeaderBehavior: allViewerAndWhitelistCloudFront
          Headers:
            - CloudFront-Viewer-Country
            - CloudFront-Viewer-Country-Name
            - CloudFront-Viewer-Country-Region
            - CloudFront-Viewer-Country-Region-Name
            - CloudFront-Viewer-City
        CookiesConfig:
          CookieBehavior: all
        QueryStringsConfig:
          QueryStringBehavior: all

Outputs:
  DisabledCachePolicyId:
    Value: !Ref DisabledCachePolicy
    Export:
      Name: !Sub ${ServiceName}-${ENV}-disabled-policy-id
  ImageCachePolicyId:
    Value: !Ref ImageCachePolicy
    Export:
      Name: !Sub ${ServiceName}-${ENV}-image-policy-id
  AssetsCachePolicyId:
    Value: !Ref AssetsCachePolicy
    Export:
      Name: !Sub ${ServiceName}-${ENV}-assets-policy-id
  JsCachePolicyId:
    Value: !Ref JsCachePolicy
    Export:
      Name: !Sub ${ServiceName}-${ENV}-js-policy-id
  DefaultCachePolicyId:
    Value: !Ref DefaultCachePolicy
    Export:
      Name: !Sub ${ServiceName}-${ENV}-default-policy-id
  1minCachePolicyId:
    Value: !Ref 1minCachePolicy
    Export:
      Name: !Sub ${ServiceName}-${ENV}-1min-policy-id
  DisabledOriginRequestPolicyId:
    Value: !Ref DisabledOriginRequestPolicy
    Export:
      Name: !Sub ${ServiceName}-${ENV}-disabled-origin-request-policy-id
  AllViewerPolicyId:
    Value: !Ref AllViewerPolicy
    Export:
      Name: !Sub ${ServiceName}-${ENV}-allviewer-policy-id
  GeolocationHeadersPolicyId:
    Value: !Ref GeolocationHeadersPolicy
    Export:
      Name: !Sub ${ServiceName}-${ENV}-geolocation-policy-id
  StaticCachePolicyId:
    Value: !Ref StaticCachePolicy
    Export:
      Name: !Sub ${ServiceName}-${ENV}-static-cache-policy-id
  AllViewerAndCloudFrontPolicyId:
    Value: !Ref AllViewerAndCloudFrontPolicy
    Export:
      Name: !Sub ${ServiceName}-${ENV}-allviewer-cloudfront-policy-id