AWSTemplateFormatVersion: '2010-09-09'
#スタックパラメーター設定
Parameters:
  #環境名
  ENV:
    Type: String
    AllowedValues: ['prod', 'stg', 'dev']
    ConstraintDescription: Enter prod, stg, or dev."
  #サービス名
  ServiceName:
    Type: String
    AllowedPattern: ^[a-z0-9-]*$
    Default: play-store
    ConstraintDescription: Malformed input-Parameter ServiceName must match pattern [a-z0-9-]+
    Description: Enter service name, like 「play-store」

Resources:
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${ENV}-task-execution-role
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      - arn:aws:iam::aws:policy/AmazonSSMFullAccess

  ECSTaskRoleForDynamoDB:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${ENV}-ecs-task-dynamodb-role
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      - arn:aws:iam::aws:policy/AmazonSSMFullAccess

  ECSTaskRoleForS3:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${ENV}-ecs-task-s3-role
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      - arn:aws:iam::aws:policy/AmazonSSMFullAccess

  ECSTaskRoleForMercury:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${ENV}-ecs-task-for-mercury-role
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      - arn:aws:iam::aws:policy/AmazonSSMFullAccess

  ECSTaskRoleForAriel:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${ENV}-ecs-task-for-ariel-role
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      - arn:aws:iam::aws:policy/AmazonSQSFullAccess
      - arn:aws:iam::aws:policy/AmazonSSMFullAccess

  ECSTaskRoleForDDBAndGlue:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${ENV}-ecs-task-for-ddb-glue-role
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      - arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess
      - arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/AmazonSSMFullAccess

  ECSTaskRoleForDDBAndS3:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${ENV}-ecs-task-for-ddb-s3-role
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/AmazonSSMFullAccess

  ECSTaskRoleForCFnAndS3:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${ENV}-ecs-task-for-cfn-s3-role
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/AdministratorAccess
      - arn:aws:iam::aws:policy/AmazonSSMFullAccess

  ECSTaskRoleForAdministratorAccess:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${ENV}-ecs-task-for-admin-access-role
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      - arn:aws:iam::aws:policy/AdministratorAccess

  ECSTaskRoleForAdministratorAccess:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${ENV}-ecs-task-for-admin-access-role
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      - arn:aws:iam::aws:policy/AdministratorAccess

  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${ENV}-ecs-service-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole'

  EC2DeployServerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${ENV}-ec2-deploy-server-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/ElasticLoadBalancingReadOnly'

  S3AccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${ENV}-s3-full-access
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'

  ApiGatewayCloudWatchLogsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${ENV}-api-gateway-cw-logs-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'

  GitHubOidcRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${ENV}-github-openid-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated:
                - !Ref GithubOidc
            Condition:
                StringEquals:
                  token.actions.githubusercontent.com:aud: sts.amazonaws.com
                StringLike:
                  token.actions.githubusercontent.com:sub: repo:play-video-stores/*:*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess

  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - a031c46782e6e6c662c2c87c76da9aa62ccabd8e

Outputs:
  ECSTaskExecutionRoleARN:
    Value: !GetAtt  ECSTaskExecutionRole.Arn
    Export:
      Name: !Sub ${ServiceName}-${ENV}-ecs-task-execution-role-arn
  ECSTaskRoleForDynamoDBARN:
    Value: !GetAtt  ECSTaskRoleForDynamoDB.Arn
    Export:
      Name: !Sub ${ServiceName}-${ENV}-ecs-task-dynamodb-role-arn
  ECSTaskRoleForS3:
    Value: !GetAtt  ECSTaskRoleForS3.Arn
    Export:
      Name: !Sub ${ServiceName}-${ENV}-ecs-task-s3-role-arn
  ECSTaskRoleForMercury:
    Value: !GetAtt  ECSTaskRoleForMercury.Arn
    Export:
      Name: !Sub ${ServiceName}-${ENV}-ecs-task-for-mercury-role
  ECSTaskRoleForAriel:
    Value: !GetAtt  ECSTaskRoleForAriel.Arn
    Export:
      Name: !Sub ${ServiceName}-${ENV}-ecs-task-for-ariel-role
  ECSServiceRoleARN:
    Value: !GetAtt  ECSServiceRole.Arn
    Export:
      Name: !Sub ${ServiceName}-${ENV}-ecs-service-role
  ECSTaskRoleForDDBAndGlue:
    Value: !GetAtt  ECSTaskRoleForDDBAndGlue.Arn
    Export:
      Name: !Sub ${ServiceName}-${ENV}-ecs-task-for-ddb-glue-role
  ECSTaskRoleForDDBAndS3:
    Value: !GetAtt  ECSTaskRoleForDDBAndS3.Arn
    Export:
      Name: !Sub ${ServiceName}-${ENV}-ecs-task-for-ddb-s3-role
  ECSTaskRoleForCFnAndS3:
    Value: !GetAtt  ECSTaskRoleForCFnAndS3.Arn
    Export:
      Name: !Sub ${ServiceName}-${ENV}-ecs-task-for-cfn-s3-role
  ECSTaskRoleForAdministratorAccess:
    Value: !GetAtt  ECSTaskRoleForAdministratorAccess.Arn
    Export:
      Name: !Sub ${ServiceName}-${ENV}-ecs-task-for-admin-access-role
  S3AccessRole:
    Value: !GetAtt  S3AccessRole.Arn
    Export:
      Name: !Sub ${ServiceName}-${ENV}-s3-access-role
  ApiGatewayCloudWatchLogsRole:
    Value: !GetAtt  ApiGatewayCloudWatchLogsRole.Arn
    Export:
      Name: !Sub ${ServiceName}-${ENV}-api-gateway-cw-logs-role
  GitHubOidcRole:
    Value: !GetAtt  GitHubOidcRole.Arn
    Export:
      Name: !Sub ${ServiceName}-${ENV}-github-openid-role